{% set version = "2.8.0.6" %}
{% set arm_variant_type = arm_variant_type | default("sbsa") %}
{% set cuda_compiler_version = cuda_compiler_version | default("None") %}

package:
  name: cutensor
  version: {{ version }}

source:
  - url: "https://developer.download.nvidia.com/compute/cutensor/redist/libcutensor/linux-x86_64/libcutensor-linux-x86_64-{{ version }}_cuda12-archive.tar.xz"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("12")]
    sha256: "a265120c0e64723e9f43aa03ca51af55126d0f8266c256e003ced8340f7fa966"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("12")]
  - url: "https://developer.download.nvidia.com/compute/cutensor/redist/libcutensor/linux-x86_64/libcutensor-linux-x86_64-{{ version }}_cuda13-archive.tar.xz"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("13")]
    sha256: "2a1a37e4c030b779748ea2f4cda3c283ea5613f7ed9f24d03adf524c7455f98e"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("13")]
  - url: "https://developer.download.nvidia.com/compute/cutensor/redist/libcutensor/linux-sbsa/libcutensor-linux-sbsa-{{ version }}_cuda12-archive.tar.xz"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa"]
    sha256: "b9c391c8e9c4752f03b37b8c57058ac513a477f5388d708743ed46222355f849"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa"]
  - url: "https://developer.download.nvidia.com/compute/cutensor/redist/libcutensor/linux-sbsa/libcutensor-linux-sbsa-{{ version }}_cuda13-archive.tar.xz"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa"]
    sha256: "cbe3069e9776c2b4421f5d13c01011352a16929caad3b1eaf74839ee91e6768e"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa"]
  - url: "https://developer.download.nvidia.com/compute/cutensor/redist/libcutensor/windows-x86_64/libcutensor-windows-x86_64-{{ version }}_cuda12-archive.zip"  # [win and x86_64 and (cuda_compiler_version or "").startswith("12")]
    sha256: "735b4c187fb03940d877ee930a72445a51c856572a7965951fd3b4a855baafa0"  # [win and x86_64 and (cuda_compiler_version or "").startswith("12")]
  - url: "https://developer.download.nvidia.com/compute/cutensor/redist/libcutensor/windows-x86_64/libcutensor-windows-x86_64-{{ version }}_cuda13-archive.zip"  # [win and x86_64 and (cuda_compiler_version or "").startswith("13")]
    sha256: "243faec3eb504adeba4531457a94fbf0d041c92e024d0ca38ad73856676f330b"  # [win and x86_64 and (cuda_compiler_version or "").startswith("13")]

build:
  number: 0
  skip: true  # [cuda_compiler_version in (undefined, "None")]
  run_exports:
    - {{ pin_subpackage('cutensor') }}
  ignore_run_exports_from:
    - {{ compiler('cuda') }}
  missing_dso_whitelist:
    - "*/libcuda.so.*"    # [linux]
    - "*/nvcuda.dll"      # [win]
  script_env:
    - cuda_major={{ cuda_major }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - arm-variant * {{ arm_variant_type }}  # [aarch64]
    - cf-nvidia-tools 1                     # [linux]
  host:
    - cuda-version {{ cuda_compiler_version }}
    - libcublas
  run:
    - {{ pin_compatible("cuda-version", min_pin="x", max_pin="x") }}
    - libcublas
  run_constrained:
    - arm-variant * {{ arm_variant_type }}  # [aarch64]

test:
  requires:
    - git
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - {{ stdlib('c') }}
    # need the libcuda stub for import test
    - cuda-driver-dev  # [linux]
  files:
    - test_load_elf.c  # [linux]

about:
  home: https://developer.nvidia.com/cutensor
  license: LicenseRef-cuTENSOR-Software-License-Agreement
  license_url: https://docs.nvidia.com/cuda/cutensor/license.html
  license_file: LICENSE
  summary: Tensor Linear Algebra on NVIDIA GPUs
  description: |
    The cuTENSOR Library is a first-of-its-kind GPU-accelerated tensor linear
    algebra library providing tensor contraction, reduction and elementwise
    operations. cuTENSOR is used to accelerate applications in the areas of
    deep learning training and inference, computer vision, quantum chemistry
    and computational physics.

    License Agreements:- The packages are governed by the NVIDIA cuTENSOR
    Software License Agreement (EULA). By downloading and using the packages,
    you accept the terms and conditions of the NVIDIA cuTENSOR EULA -
    https://docs.nvidia.com/cuda/cutensor/license.html
  doc_url: https://docs.nvidia.com/cuda/cutensor/index.html
  dev_url: https://developer.nvidia.com/cutensor/downloads

extra:
  recipe-maintainers:
    - ChrisPsa
    - b-kloss
    - conda-forge/cuda
    - v0i0
    - yangcal
    - JeremyWangNVDA
    - leofang
    - jakirkham
    - mtjrider
